### ISSUE TITLE
'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by tux-mind** [scottwernervt/favicon#22]
Hi, thanks for this awesome egg :)

I think that I found a bug when a [website](https://aol.com/) contains this meta: `<link href="" rel="shortcut icon"/>` .

This causes `tag.get('href') or tag.get('content')` at favicon.py to return `None` instead of a string.

You may want to not include metas with empty href/content into the one to parse :blush: 

Thank you in advance for your time and I wish you a great week :)

**Comment by scottwernervt** [comment]
Thanks for the bug report will look into it!

**Comment by scottwernervt** [comment]
The issue is resolved in `favicon===0.7.0`. Thanks for reporting!

**Comment by cobrax1** [comment]
> Hi, thanks for this awesome egg :)
> 
> I think that I found a bug when a [website](https://aol.com/) contains this meta: `<link href="" rel="shortcut icon"/>` .
> 
> This causes `tag.get('href') or tag.get('content')` at favicon.py to return `None` instead of a string.
> 
> You may want to not include metas with empty href/content into the one to parse 😊
> 
> Thank you in advance for your time and I wish you a great week :)

tux  mind how  can i contact u plz  ??
