### ISSUE TITLE
Incorrect location of favicon.ico 

### ISSUE THREAD

**Issue by alexjacobson95** [scottwernervt/favicon#27]
The library currently tries to find the default favicon.ico file in the wrong place. 

According to https://html.spec.whatwg.org/multipage/links.html#rel-icon: 

"In the absence of a link with the icon keyword . . . Let request be a new request whose url is the URL record obtained by resolving the URL "/favicon.ico" against the Document object's URL".

In other words the favicon.ico is stored at the site root.

Example:
Original URL: https://github.com/scottwernervt/favicon/
Correct Favicon URL: github.com/favicon.ico
Incorrect Favicon URL: github.com/scottwenervt/favicon/favicon.ico

Right now the library searches the incorrect url.

**Comment by alexjacobson95** [comment]
The issue is on: https://github.com/scottwernervt/favicon/blob/db2676b6c7cd913674ad5b23cadfa2eb3ad93b7b/src/favicon/favicon.py#L85 

Unsure how you want to fix this, but the library will need to parse the url (the defacto standard seems to be [urllib.parse.urlparse](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse)).

**Comment by scottwernervt** [comment]
I think `urlparse` should work as we can just rebuild the url as `scheme://netloc/`.
